name: Test Merge Changes

on:
  pull_request:
    branches:
      - main

jobs:
  test_pull_request_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build